apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-apache
spec:
  replicas: 2
  selector:
    matchLabels:
      app: php-apache
  template:
    metadata:
      labels:
        app: php-apache
    spec:
      containers:
      - name: php-apache
        image: php:8.2-apache
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        volumeMounts:
        - name: app-code
          mountPath: /var/www/html/index.php
          subPath: index.php
      volumes:
      - name: app-code
        configMap:
          name: php-index
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: php-index
data:
  index.php: |
    <?php
    header('Content-Type: application/json');
    function simulateCPULoad($intensity = 0.1, $duration = 100) {
        $startTime = microtime(true);
        $endTime = $startTime + ($duration / 1000);
        $operations = 0;
        while (microtime(true) < $endTime) {
            if (rand(1, 100) <= ($intensity * 100)) {
                $x = 0;
                for ($i = 0; $i < 1000; $i++) {
                    $x += sqrt($x + $i);
                }
            }
            $operations++;
        }
        return $operations;
    }
    $intensity = isset($_GET['intensity']) ? floatval($_GET['intensity']) : 0.5;
    $duration = isset($_GET['duration']) ? intval($_GET['duration']) : 100;
    $intensity = max(0.1, min(1.0, $intensity));
    $duration = max(50, min(500, $duration));
    $startTime = microtime(true);
    $memoryBefore = memory_get_usage();
    $operations = simulateCPULoad($intensity, $duration);
    $executionTime = (microtime(true) - $startTime) * 1000;
    $memoryUsed = memory_get_usage() - $memoryBefore;
    echo json_encode([
        'status' => 'success',
        'request' => [
            'intensity' => $intensity,
            'duration' => $duration
        ],
        'metrics' => [
            'execution_time_ms' => round($executionTime, 2),
            'memory_used_bytes' => $memoryUsed,
            'operations_performed' => $operations,
            'operations_per_ms' => round($operations / $executionTime, 2)
        ],
        'timestamp' => time(),
        'server_info' => [
            'php_version' => PHP_VERSION,
            'server_time' => date('c')
        ]
    ], JSON_PRETTY_PRINT);
---
apiVersion: v1
kind: Service
metadata:
  name: php-apache
spec:
  selector:
    app: php-apache
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
  type: NodePort
